# Numpy 1 D-array

In [3]:
import numpy as np
a = np.array([5,5,5])
a

array([5, 5, 5])

In [4]:
type(a)

numpy.ndarray

In [5]:
len(a)

3

In [6]:
a[0]

5

In [7]:
a[0:]

array([5, 5, 5])

In [9]:
a = np.zeros(2)
a

array([0., 0.])

In [10]:
a = np.ones(3)
a

array([1., 1., 1.])

In [11]:
a = np.empty(3)
a

array([1., 1., 1.])

In [12]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [13]:
a = np.arange(2, 20)
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [14]:
a = np.arange(2,20,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
a = np.linspace(0,10, num=5)
a

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [17]:
a = np.ones(5, dtype=np.int8)
a

array([1, 1, 1, 1, 1], dtype=int8)

In [18]:
a = np.ones(3, dtype=np.float64)
a

array([1., 1., 1.])

# Numpy 2D-array

In [8]:
b = np.array([[5,5,5], [5,5,5]])
b

array([[5, 5, 5],
       [5, 5, 5]])

In [20]:
b = np.zeros((3,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [22]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Creating an array using Numpy

In [2]:
import numpy as np
food = np.array(["Pakora", "Samosa", "Raita" ])
food

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [3]:
price = np.array([5, 5, 5])
price

array([5, 5, 5])

In [4]:
type(price)

numpy.ndarray

In [5]:
type(food)

numpy.ndarray

In [6]:
len(food)

3

In [7]:
price[0]

5

In [10]:
price[0:]

array([5, 5, 5])

In [11]:
food[1]

'Samosa'

In [12]:
price.mean()

5.0

In [13]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
#specify
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [19]:
# specific interval
np.arange(3,20,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [21]:
# table of 5
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [22]:
# linespace
np.linspace(1, 10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [25]:
np.ones(20, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [24]:
np.zeros(20, dtype=np.int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

# Array functions

In [27]:
a = np.array([10,15,40,30,50,100,35,13,9,0.5,100.4,320])
a

array([ 10. ,  15. ,  40. ,  30. ,  50. , 100. ,  35. ,  13. ,   9. ,
         0.5, 100.4, 320. ])

### Sort function

In [31]:
a.sort()
a

array([  0.5,   9. ,  10. ,  13. ,  15. ,  30. ,  35. ,  40. ,  50. ,
       100. , 100.4, 320. ])

In [32]:
b = np.array([10.4,3.1,40.7,11.5,13.2,60.9])
b

array([10.4,  3.1, 40.7, 11.5, 13.2, 60.9])

In [36]:
c = np.concatenate((a,b))
c

array([  0.5,   9. ,  10. ,  13. ,  15. ,  30. ,  35. ,  40. ,  50. ,
       100. , 100.4, 320. ,  10.4,   3.1,  40.7,  11.5,  13.2,  60.9])

In [37]:
c.sort()
c

array([  0.5,   3.1,   9. ,  10. ,  10.4,  11.5,  13. ,  13.2,  15. ,
        30. ,  35. ,  40. ,  40.7,  50. ,  60.9, 100. , 100.4, 320. ])

# 2D Array

In [3]:
import numpy as np
a = np.array([[1,2,3,4,5],[5,4,3,2,1]])
a

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [6]:
b = np.array([[6,7], [8,9]])
b

array([[6, 7],
       [8, 9]])

In [7]:
x = np.array([[1,2],[5,4]])
x

array([[1, 2],
       [5, 4]])

In [8]:
y = np.array([[6,7],[7,8]])
y

array([[6, 7],
       [7, 8]])

### concatenate

In [9]:
np.concatenate((x,y))

array([[1, 2],
       [5, 4],
       [6, 7],
       [7, 8]])

In [10]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [5, 4],
       [6, 7],
       [7, 8]])

In [11]:
np.concatenate((x,y), axis=1)

array([[1, 2, 6, 7],
       [5, 4, 7, 8]])

In [13]:
a = np.array([[[0,1,2,3],[4,5,6,7]],[[0,1,2,3],[4,5,6,7]],[[0,1,2,3],[4,5,6,7]]])
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [14]:
# To find the number of dimentions
a.ndim

3

In [15]:
b =np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
a.size

24

In [18]:
a.shape

(3, 2, 4)

In [20]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
b = a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
# Convert 1D into 2D
a = np.array([1,2,3,4,5,6,7,8,9])
a
a.shape

(9,)

In [29]:
# Rowwise 2D
b = a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [30]:
b.shape

(1, 9)

In [31]:
# Columnwise 2D
c = a[: ,np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [32]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [35]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [36]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [39]:
a.sum()

45

In [40]:
a.mean()

5.0